language: python
python:
  - "2.7"
install:
  - pip install --timeout=30 pep8 --use-mirrors
  - pip install --timeout=30 pyflakes --use-mirrors
  - pip install --timeout=30 -r requirements.txt --use-mirrors --allow-external fs --allow-unverified fs
  - pip install --timeout=30 -q -e . --use-mirrors
before_script:
  - make verify
script:
  make test
after_success:
  coveralls
